### ISSUE TITLE
[Feature]delect video cache

### ISSUE THREAD

**Issue by cangming99** [DeathWrench/YoutubeDownloader#1]
Can an option be added to clear the downloaded video cache each time the game is closed?

**Comment by DeathWrench** [comment]
So you want the videos to be gone whenever you start the game?

**Comment by cangming99** [comment]
I’m sorry, I thought this mod would allow other players to download the video synchronously and watch the same video together. So, I wanted them to clear the previous cache when they reopen the game. However, I just tried it with a friend, and it turns out that only I can see the video.

**Comment by DeathWrench** [comment]
Either way, added an option to delete downloaded videos.
