### ISSUE TITLE
Mod doesn't seem to load on startup 

### ISSUE THREAD

**Issue by FweeGamerHD** [DeathWrench/YoutubeDownloader#2]
title.

following errors related to this mod also show up in the console
![image](https://github.com/DeathWrench/YoutubeDownloader/assets/59413930/f4e4791b-bc2f-431a-8c4b-f502795c1475)

So far, even on a profile without any other mods than those required by this one, I've not been able to get the mod to load.

**Comment by DeathWrench** [comment]
You have all of the dependencies? Make sure you don't have TVLoader/LethalTVManager installed.
![image](https://github.com/DeathWrench/YoutubeDownloader/assets/45341450/02a4f827-1c93-4417-9b3d-301e8553a2b5)

**Comment by FweeGamerHD** [comment]
Well yea, r2modman takes care of those.
You can also see that there's an error with the bestest tv mod. Possibly more of an issue of that mod?

**Comment by DeathWrench** [comment]
in `BepinEx.cfg` you have to set `HideManagerGameObject = true`

**Comment by FweeGamerHD** [comment]
Setting this to true seems to have fixed the issue now. Might be something to consider mentioning on the modpage for others that might have the same issue.

**Comment by DeathWrench** [comment]
> Setting this to true seems to have fixed the issue now. Might be something to consider mentioning on the modpage for others that might have the same issue.

I did [here](https://thunderstore.io/c/lethal-company/p/DeathWrench/ScaleableShip/), a lot of mods seem to require it, got an idea for a small update so I can make an excuse to update the ReadMe.
